allowBuilds:
  "@img/sharp-darwin-arm64": true
  "@img/sharp-libvips-darwin-arm64": true
  esbuild: true
  msw: true
  sharp: true
minimumReleaseAgeExclude:
  - astro@6.3.7 || 7.2.3
  - '@astrojs/internal-helpers@0.10.3'
  - '@astrojs/markdown-remark@7.2.3'
  - '@astrojs/markdown-satteri@0.3.6'
  - '@astrojs/mdx@7.0.6'
  - '@astrojs/react@6.0.3'
